"use strict";
exports.reduxConstants = {
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    SUCCESS_LOGOUT: 'SUCCESS_LOGOUT',
    ERROR_LOGIN: 'ERROR_LOGIN',
    COURSE_CREATED: 'COURSE_CREATED',
    COURSE_DELETED: 'COURSE_DELETED',
    COURSE_UPDATED: 'COURSE_UPDATED',
    COURSES_UPDATED: 'COURSES_UPDATED',
    COURSES_NAVIGATE: 'COURSES_NAVIGATE'
};
